# Generated by Django 2.0 on 2018-03-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('siblings_and_spouse_count', models.IntegerField()),
                ('parent_and_children_count', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('ticket_number', models.CharField(max_length=100)),
                ('passenger_class', models.CharField(max_length=10)),
                ('cabin_number', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('port_of_embarkation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survival_prediction', models.IntegerField(default=1)),
                ('prediction_confidence', models.IntegerField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titanic.Passenger')),
            ],
        ),
    ]
