# Generated by Django 2.0 on 2018-03-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
